public with sharing class EmailManager {
    public static void sendMail(List<Messaging.SingleEmailMessage> mails) {
        Messaging.SendEmailResult[] results = Messaging.sendEmail(mails);
        inspectResults(results);
    }
    private static Boolean inspectResults(Messaging.SendEmailResult[] results) {
        Boolean sendResult = true;
        for (Messaging.SendEmailResult res : results) {
            if (res.isSuccess()) {
                System.debug('Email sent successfully');
            }
            else {
                sendResult = false;
                System.debug('The following errors occurred: ' + res.getErrors());
            }
        }
        return sendResult;
    }
}